### PR TITLE
Add requirements and fix the error in import.py

### PR DESCRIPTION
**Pull request by Senthi1Kumar**
Hi @iamleonie, I've fixed the `UnicodeDecodeError` in the `import.py` and added requirements.txt

Contribution to https://github.com/weaviate-tutorials/DEMO-semantic-search-podcast/issues/1

### CODE REVIEW

**Review by iamleonie — APPROVED** [review]

**Comment by iamleonie** [comment]
Thank you for your contribution!

**Comment by Senthi1Kumar** [comment]
For the podcast audio data, I've some queries,
- I think the mp3 files from the feed (xml) by parsing it is the good idea for this issue.
- The final output of transcripts from the Whisper model, should be like in the `data/podcast_ds.json`?. And I tried with **tiny** & **base** models, the transcript is not like in json file like conversational, instead it transcribes as a whole text of the audio as from below image and you see it only transcribes the 30sec duration and trying to solve this to generate for longer duration:
image

**Comment by Senthi1Kumar** [comment]
> For the podcast audio data, I've some queries,
> 
>     * I think the mp3 files from the feed (xml) by parsing it is the good idea for this issue.
> 
>     * The final output of transcripts from the Whisper model, should be like in the `data/podcast_ds.json`?. And I tried with **tiny** & **base** models, the transcript is not like in json file like conversational, instead it transcribes as a whole text of the audio as from below image and you see it only transcribes the 30sec duration and trying to solve this to generate for longer duration:
>       image

Hello @iamleonie, please look at this :)

**Comment by iamleonie** [comment]
Hi @IamSenthilKumar,
Yes, I think if you could keep the rough structure on the podcast_ds.json file (title, URL, transcript) that would be great. But I don't think the transcript doesn't have to follow the conversational style ('Speaker A: ...., Speaker B:..., Speaker A:...). Instead for a first iteration it would be sufficient to just have one big corpus of the conversation (no speaker identification). 
If it is only possible to transcript 30s snippets, how about chunking the input into 30s snippets?

**Comment by Senthi1Kumar** [comment]
Hi @iamleonie, i tried using OpenAI's whiper python library, and used `pydub` to create chunks, but i didn't make it with whisper library, if time permits I'll finish it. Yet, I am using `transformer` library with the whisper model from the HF hub to generate it, is it ok?

Thank you

**Comment by iamleonie** [comment]
Hey @IamSenthilKumar, I think that should be no problem.

**Pull request merged**
